cask "font-dinish" do
  version "4.006"

  url "https://github.com/playbeing/dinish/releases/download/v#{version}/DINish-otf.zip"
  name "DINish"
  desc "Open-source font inspired by German Autobahn road sign lettering"
  homepage "https://fonts.playbeing.com/dinish/"

  font "DINish-Black.otf"
  font "DINish-BlackItalic.otf"
  font "DINish-Bold.otf"
  font "DINish-BoldItalic.otf"
  font "DINish-Heavy.otf"
  font "DINish-HeavyItalic.otf"
  font "DINish-Italic.otf"
  font "DINish-Light.otf"
  font "DINish-LightItalic.otf"
  font "DINish-Medium.otf"
  font "DINish-MediumItalic.otf"
  font "DINish-Regular.otf"
  font "DINish-SemiBold.otf"
  font "DINish-SemiBoldItalic.otf"
  font "DINishCondensed-Black.otf"
  font "DINishCondensed-BlackItalic.otf"
  font "DINishCondensed-Bold.otf"
  font "DINishCondensed-BoldItalic.otf"
  font "DINishCondensed-Heavy.otf"
  font "DINishCondensed-HeavyItalic.otf"
  font "DINishCondensed-Italic.otf"
  font "DINishCondensed-Light.otf"
  font "DINishCondensed-LightItalic.otf"
  font "DINishCondensed-Medium.otf"
  font "DINishCondensed-MediumItalic.otf"
  font "DINishCondensed-Regular.otf"
  font "DINishCondensed-SemiBold.otf"
  font "DINishCondensed-SemiBoldItalic.otf"
  font "DINishExpanded-Black.otf"
  font "DINishExpanded-BlackItalic.otf"
  font "DINishExpanded-Bold.otf"
  font "DINishExpanded-BoldItalic.otf"
  font "DINishExpanded-Heavy.otf"
  font "DINishExpanded-HeavyItalic.otf"
  font "DINishExpanded-Italic.otf"
  font "DINishExpanded-Light.otf"
  font "DINishExpanded-LightItalic.otf"
  font "DINishExpanded-Medium.otf"
  font "DINishExpanded-MediumItalic.otf"
  font "DINishExpanded-Regular.otf"
  font "DINishExpanded-SemiBold.otf"
  font "DINishExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end
